name: "CICD_ForDemo_ToAzure"

on: workflow_dispatch

jobs:
  Run-DAI-Test-Configuration:
    strategy: # Optional configuration by using matrix strategy
      max-parallel: 1 # To set the maximum number of jobs that can run simultaneously 
    runs-on: ubuntu-latest
    name: Run Test Configuration
    steps:
      - run: echo "Trigger event.. ${{ github.event_name }}. Runner OS.. ${{ runner.os }}."
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@v1.0.10
        with:
          serverURL: "https://eval.dai.eggplant.cloud"
          testConfigID: "17a3e7ec-f089-4456-8e1f-f9a44c359037"
          clientID: "client:dai:api:integration:e224b80d-13c5-4467-afef-172422836510"
          clientSecret: "F6Lcz6mexVlLCiZHCA9kA21uVuSgnUaO"
          testResultPath: "result.xml"
          
      - name: "Import results to Xray"
        run: | 
          token=$(curl -s -H "Content-Type: application/json" -X POST --data '{"client_id": "7951640B37F54D4894603420F37B4F8F", "client_secret": "8d5582f037f927c032eee6349ed1a10523918cadc8a14640e95412b6af54345f" }' https://xray.cloud.getxray.app/api/v2/authenticate);
          echo "Authentication token=$token"; 
          response=$(curl -s -H "Content-Type: text/xml" -X POST -H "Authorization: Bearer ${token:1: -1}" --data @"result.xml" https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=JZXP);
          echo "Xray issue=$response"


 
